name: Fetch MrBeast Subs

on:
  schedule:
    - cron: "*/1 * * * *" # toutes les 1 minute
  workflow_dispatch: # exécution manuelle

jobs:
  fetch_subs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch subscriber count
        run: |
          curl -s https://backend.mixerno.space/api/youtube/estv3/UCX6OQ3DkcsbYNE6H8uQQuVA \
          | jq '{subscriberCount: .items[0].statistics.subscriberCount}' > mrbeast.json

      - name: Commit and push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add mrbeast.json
          git commit -m "Update subscriber count [skip ci]" || echo "No changes to commit"
          git push
